[package]
edition = "2024"
name = "numin"
version = { workspace = true }

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
thiserror = "2.0.12"
widestring = "1.2.0"
windows = { version = "0.61.1", features = [
    "Win32_System_LibraryLoader",
    "Win32_System_SystemServices",
    "Win32_Media_KernelStreaming",
] }

[build-dependencies]
reqwest = { version = "0.12.15", features = ["blocking"] }
