[workspace]
members = ["common", "numin"]
package.version = "0.1.4"

[package]
edition = "2024"
name = "miniature"
version = { workspace = true }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true

[profile.dev]
panic = "abort"

[dependencies]
common = { path = "./common", default-features = false, features = [
    "crt_functions",
] }
compiler_builtins_but_not_named_that = { version = "0.1", features = [
    "mem",
], package = "compiler_builtins" }
widestring = { version = "1.2", default-features = false, features = ["alloc"] }
windows = { version = "0.62", default-features = false, features = [
    "Win32_Security",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Registry",
    "Win32_System_JobObjects",
    "Win32_Storage_FileSystem",
    "Win32_System_Threading",
    "Win32_System_Console",
    "Win32_System_IO",
    "Win32_System_Environment",
    "Win32_System_Memory",
] }

[build-dependencies]
cc = "1.2"
which = "8.0"
winres = "0.1"
