[package]
edition = "2021"
name = "miniature"
version = "0.1.0"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true

[profile.dev]
panic = "abort"

[dependencies]
widestring = { version = "1.2", default-features = false, features = ["alloc"] }
windows = { version = "0.61", default-features = false, features = [
    "Win32_Security",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Registry",
    "Win32_System_JobObjects",
    "Win32_Storage_FileSystem",
    "Win32_System_Threading",
    "Win32_System_Console",
    "Win32_System_IO",
    "Win32_System_Environment",
    "Win32_System_Memory",
] }

[build-dependencies]
which = "7.0.2"
winres = "0.1.12"
