[build]
rustflags = [
    "-Zlocation-detail=none",
    "-Cpanic=abort",
    "-Ctarget-feature=+crt-static",
]
target = "x86_64-pc-windows-msvc"

[unstable]
build-std = ["core", "alloc", "std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]
