[package]
edition = "2024"
name = "common"
version.workspace = true

[features]
crt_functions = []
default = ["std"]
std = []

[dependencies]
widestring = { version = "1.2.0", default-features = false, features = [
    "alloc",
] }
windows = { version = "0.62.0", default-features = false, features = [
    "Win32_Storage_FileSystem",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
] }

[build-dependencies]
cc = "1.2.19"
