on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

name: "Build"

jobs:
  build:
    name: Build for ${{ matrix.arch }}
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
          - i686
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.8.1

      - name: Build miniature
        run: cargo build --release --locked --target ${{ matrix.arch }}-pc-windows-msvc

      - name: Build Numin
        env:
          MINIATURE_EXE_PATH: ${{ github.workspace }}/target/${{ matrix.arch }}-pc-windows-msvc/release/miniature.exe
        run: cargo build --release --locked --target ${{ matrix.arch }}-pc-windows-msvc -p numin
