on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

name: "Build"

jobs:
  build-shim:
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
          # - i686
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.8

      - name: Build miniature
        run: cargo build --release --locked --target ${{ matrix.arch }}-pc-windows-msvc
  build-numin:
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
          - i686
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.8

      - name: Build Numin
        run: cargo build --release --locked --target ${{ matrix.arch }}-pc-windows-msvc -p numin
