name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish:
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
          - i686
    name: Publish
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6.0.0

      - name: Build miniature
        run: cargo b --release --locked --target ${{ matrix.arch }}-pc-windows-msvc

      - name: Build Numin
        env:
          MINIATURE_EXE_PATH: ${{ github.workspace }}/target/${{ matrix.arch }}-pc-windows-msvc/release/miniature.exe
        run: cargo b --release --locked -p numin --target ${{ matrix.arch }}-pc-windows-msvc

      - name: Rename build artifacts
        run: |
          mkdir artifacts
          mv target/${{ matrix.arch }}-pc-windows-msvc/release/miniature.exe artifacts/miniature-${{ matrix.arch }}.exe
          mv target/${{ matrix.arch }}-pc-windows-msvc/release/numin.exe artifacts/numin-${{ matrix.arch }}.exe

      - name: Upload & Publish
        uses: softprops/action-gh-release@v2.3.2
        with:
          files: |
            artifacts/*.exe
